/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_drafts/camera-momory': RouteRecordInfo<
      '/_drafts/camera-momory',
      '/_drafts/camera-momory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_drafts/on-the-way-home': RouteRecordInfo<
      '/_drafts/on-the-way-home',
      '/_drafts/on-the-way-home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/diary/2023.10.28': RouteRecordInfo<
      '/posts/diary/2023.10.28',
      '/posts/diary/2023/10/28',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/diary/2023.9.10': RouteRecordInfo<
      '/posts/diary/2023.9.10',
      '/posts/diary/2023/9/10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/diary/about-my-senior-life': RouteRecordInfo<
      '/posts/diary/about-my-senior-life',
      '/posts/diary/about-my-senior-life',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/diary/summer-book-list': RouteRecordInfo<
      '/posts/diary/summer-book-list',
      '/posts/diary/summer-book-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/forget': RouteRecordInfo<
      '/posts/essay/forget',
      '/posts/essay/forget',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/new-college-start': RouteRecordInfo<
      '/posts/essay/new-college-start',
      '/posts/essay/new-college-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/set-up-forum': RouteRecordInfo<
      '/posts/essay/set-up-forum',
      '/posts/essay/set-up-forum',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/summary-2021': RouteRecordInfo<
      '/posts/essay/summary-2021',
      '/posts/essay/summary-2021',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/summary-2023': RouteRecordInfo<
      '/posts/essay/summary-2023',
      '/posts/essay/summary-2023',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/summary-2024': RouteRecordInfo<
      '/posts/essay/summary-2024',
      '/posts/essay/summary-2024',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/essay/summary-2025': RouteRecordInfo<
      '/posts/essay/summary-2025',
      '/posts/essay/summary-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/note/how-to-write-a-random-number-program': RouteRecordInfo<
      '/posts/note/how-to-write-a-random-number-program',
      '/posts/note/how-to-write-a-random-number-program',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/note/html-basic': RouteRecordInfo<
      '/posts/note/html-basic',
      '/posts/note/html-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/note/html-website-deployment-platform': RouteRecordInfo<
      '/posts/note/html-website-deployment-platform',
      '/posts/note/html-website-deployment-platform',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/note/my-first-post': RouteRecordInfo<
      '/posts/note/my-first-post',
      '/posts/note/my-first-post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/share/a-letter-for-you': RouteRecordInfo<
      '/posts/share/a-letter-for-you',
      '/posts/share/a-letter-for-you',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/share/how-to-install-windows-by-pe': RouteRecordInfo<
      '/posts/share/how-to-install-windows-by-pe',
      '/posts/share/how-to-install-windows-by-pe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/share/introduction': RouteRecordInfo<
      '/posts/share/introduction',
      '/posts/share/introduction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/share/win10-20h2': RouteRecordInfo<
      '/posts/share/win10-20h2',
      '/posts/share/win10-20h2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/share/win10-20h2-2': RouteRecordInfo<
      '/posts/share/win10-20h2-2',
      '/posts/share/win10-20h2-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sub/': RouteRecordInfo<
      '/sub/',
      '/sub',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.25_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/_drafts/camera-momory.md': {
      routes:
        | '/_drafts/camera-momory'
      views:
        | never
    }
    'pages/_drafts/on-the-way-home.md': {
      routes:
        | '/_drafts/on-the-way-home'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.10_@babel+parser@7.28.5_@nuxt+kit@3.16.0_@types+markdown-it@14.1.2_@types+node@22_vaoxdbustfrzff7sioaz2vuwde/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.25_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.25_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/diary/2023.10.28.md': {
      routes:
        | '/posts/diary/2023.10.28'
      views:
        | never
    }
    'pages/posts/diary/2023.9.10.md': {
      routes:
        | '/posts/diary/2023.9.10'
      views:
        | never
    }
    'pages/posts/diary/about-my-senior-life.md': {
      routes:
        | '/posts/diary/about-my-senior-life'
      views:
        | never
    }
    'pages/posts/diary/summer-book-list.md': {
      routes:
        | '/posts/diary/summer-book-list'
      views:
        | never
    }
    'pages/posts/essay/forget.md': {
      routes:
        | '/posts/essay/forget'
      views:
        | never
    }
    'pages/posts/essay/new-college-start.md': {
      routes:
        | '/posts/essay/new-college-start'
      views:
        | never
    }
    'pages/posts/essay/set-up-forum.md': {
      routes:
        | '/posts/essay/set-up-forum'
      views:
        | never
    }
    'pages/posts/essay/summary-2021.md': {
      routes:
        | '/posts/essay/summary-2021'
      views:
        | never
    }
    'pages/posts/essay/summary-2023.md': {
      routes:
        | '/posts/essay/summary-2023'
      views:
        | never
    }
    'pages/posts/essay/summary-2024.md': {
      routes:
        | '/posts/essay/summary-2024'
      views:
        | never
    }
    'pages/posts/essay/summary-2025.md': {
      routes:
        | '/posts/essay/summary-2025'
      views:
        | never
    }
    'pages/posts/note/how-to-write-a-random-number-program.md': {
      routes:
        | '/posts/note/how-to-write-a-random-number-program'
      views:
        | never
    }
    'pages/posts/note/html-basic.md': {
      routes:
        | '/posts/note/html-basic'
      views:
        | never
    }
    'pages/posts/note/html-website-deployment-platform.md': {
      routes:
        | '/posts/note/html-website-deployment-platform'
      views:
        | never
    }
    'pages/posts/note/my-first-post.md': {
      routes:
        | '/posts/note/my-first-post'
      views:
        | never
    }
    'pages/posts/share/a-letter-for-you.md': {
      routes:
        | '/posts/share/a-letter-for-you'
      views:
        | never
    }
    'pages/posts/share/how-to-install-windows-by-pe.md': {
      routes:
        | '/posts/share/how-to-install-windows-by-pe'
      views:
        | never
    }
    'pages/posts/share/introduction.md': {
      routes:
        | '/posts/share/introduction'
      views:
        | never
    }
    'pages/posts/share/win10-20h2.md': {
      routes:
        | '/posts/share/win10-20h2'
      views:
        | never
    }
    'pages/posts/share/win10-20h2-2.md': {
      routes:
        | '/posts/share/win10-20h2-2'
      views:
        | never
    }
    'pages/sub/index.md': {
      routes:
        | '/sub/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
