/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_drafts/camera-momory': RouteRecordInfo<'/_drafts/camera-momory', '/_drafts/camera-momory', Record<never, never>, Record<never, never>>,
    '/_drafts/on-the-way-home': RouteRecordInfo<'/_drafts/on-the-way-home', '/_drafts/on-the-way-home', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/diary/2023.10.28': RouteRecordInfo<'/posts/diary/2023.10.28', '/posts/diary/2023/10/28', Record<never, never>, Record<never, never>>,
    '/posts/diary/2023.9.10': RouteRecordInfo<'/posts/diary/2023.9.10', '/posts/diary/2023/9/10', Record<never, never>, Record<never, never>>,
    '/posts/diary/about-my-senior-life': RouteRecordInfo<'/posts/diary/about-my-senior-life', '/posts/diary/about-my-senior-life', Record<never, never>, Record<never, never>>,
    '/posts/diary/summer-book-list': RouteRecordInfo<'/posts/diary/summer-book-list', '/posts/diary/summer-book-list', Record<never, never>, Record<never, never>>,
    '/posts/essay/forget': RouteRecordInfo<'/posts/essay/forget', '/posts/essay/forget', Record<never, never>, Record<never, never>>,
    '/posts/essay/new-college-start': RouteRecordInfo<'/posts/essay/new-college-start', '/posts/essay/new-college-start', Record<never, never>, Record<never, never>>,
    '/posts/essay/set-up-forum': RouteRecordInfo<'/posts/essay/set-up-forum', '/posts/essay/set-up-forum', Record<never, never>, Record<never, never>>,
    '/posts/essay/summary-2021': RouteRecordInfo<'/posts/essay/summary-2021', '/posts/essay/summary-2021', Record<never, never>, Record<never, never>>,
    '/posts/essay/summary-2023': RouteRecordInfo<'/posts/essay/summary-2023', '/posts/essay/summary-2023', Record<never, never>, Record<never, never>>,
    '/posts/essay/summary-2024': RouteRecordInfo<'/posts/essay/summary-2024', '/posts/essay/summary-2024', Record<never, never>, Record<never, never>>,
    '/posts/note/how-to-write-a-random-number-program': RouteRecordInfo<'/posts/note/how-to-write-a-random-number-program', '/posts/note/how-to-write-a-random-number-program', Record<never, never>, Record<never, never>>,
    '/posts/note/html-basic': RouteRecordInfo<'/posts/note/html-basic', '/posts/note/html-basic', Record<never, never>, Record<never, never>>,
    '/posts/note/html-website-deployment-platform': RouteRecordInfo<'/posts/note/html-website-deployment-platform', '/posts/note/html-website-deployment-platform', Record<never, never>, Record<never, never>>,
    '/posts/note/my-first-post': RouteRecordInfo<'/posts/note/my-first-post', '/posts/note/my-first-post', Record<never, never>, Record<never, never>>,
    '/posts/share/a-letter-for-you': RouteRecordInfo<'/posts/share/a-letter-for-you', '/posts/share/a-letter-for-you', Record<never, never>, Record<never, never>>,
    '/posts/share/how-to-install-windows-by-pe': RouteRecordInfo<'/posts/share/how-to-install-windows-by-pe', '/posts/share/how-to-install-windows-by-pe', Record<never, never>, Record<never, never>>,
    '/posts/share/introduction': RouteRecordInfo<'/posts/share/introduction', '/posts/share/introduction', Record<never, never>, Record<never, never>>,
    '/posts/share/win10-20h2': RouteRecordInfo<'/posts/share/win10-20h2', '/posts/share/win10-20h2', Record<never, never>, Record<never, never>>,
    '/posts/share/win10-20h2-2': RouteRecordInfo<'/posts/share/win10-20h2-2', '/posts/share/win10-20h2-2', Record<never, never>, Record<never, never>>,
    '/sub/': RouteRecordInfo<'/sub/', '/sub', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
